=== dprevost/errorparser/DTD/errorParserOptions10.dtd
<!-- $Id$

    Document Type Definition for the options of Error Parser.
    
    Copyright (C) 2008 Daniel Prevost.
 
    This file may be distributed and/or modified under the terms of the
    MIT License as described by the Open Source Initiative
    (http://opensource.org/licenses/mit-license.php) and appearing in
    the file COPYING included in the packaging of the Error Parser software.
-->

<!--
    Usage:

    It is recommended to use the SYSTEM declaration, something like:

    <!DOCTYPE errorlist SYSTEM 
             "/usr/local/share/xml/errorParser/errorParserOptions10.dtd">

    (if Error Parser is installed in /usr/local).
    
    *********************************************************************
    
    If you want/prefer to use a PUBLIC declaration, the following public 
    identifier can be used to identify it:

     "-//Error Parser project//DTD Error Parser Options XML V1.0//EN"

    The full DOCTYPE declaration should then look like this:
    
    <!DOCTYPE errorlist PUBLIC 
           "-//Error Parser project//DTD Error Parser Options XML V1.0//EN"
           "http://errorparser.sourceforge.net/xml/errorParserOptions10.dtd">
    
-->

<!-- 
   This xml file provides the options to the errorParser program.
   
   Why a file? The number of options was getting too large. Using a file
   makes it easier to manage all these options and it will also make 
   easier to add new options in the future (as needed). 
   [Since changing options is usually something that will be done rarely
   once you are satisfy with the results, storing the options in a file 
   makes it easier to reuse the same options, evidently]
   
   Why xml? Easier to program (libxml2 does the parsing) and easy to
   provide default values for some.
   
   Note: do not modify this DTD... without modifying the code to read 
   these options in the errorParser program.
-->

<!ELEMENT options      (enumname?,header_name_dir?,header_name,
                        errmsg_dir?,errmsg_header_name,errmsg_c_name,
                        prefix_error,prefix_variable,err_msg,selected_lang?)>
<!ELEMENT enumname           (#PCDATA)>
<!ELEMENT header_name_dir    (#PCDATA)>
<!ELEMENT header_name        (#PCDATA)>
<!ELEMENT errmsg_dir         (#PCDATA)>
<!ELEMENT errmsg_header_name (#PCDATA)>
<!ELEMENT errmsg_c_name      (#PCDATA)>
<!ELEMENT prefix_error       (#PCDATA)>
<!ELEMENT prefix_variable    (#PCDATA)>
<!ELEMENT err_msg            EMPTY>
<!ELEMENT selected_lang      EMPTY>

<!ATTLIST err_msg allow_escapes (yes|no) "no">
<!ATTLIST err_msg allow_quotes  (yes|no) "yes">
<!ATTLIST err_msg percent CDATA #REQUIRED>
<!ATTLIST selected_lang xml:lang CDATA #REQUIRED>

=== dprevost/errorparser/examples/example_options.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM 
             "/usr/local/share/xml/errorParser/errorParserOptions10.dtd">
<!-- 
   This xml file provides the options to the errorParser program.
   
   Why a file? The number of options was getting too large. Using a file
   makes it easier to manage all these options and it will also make 
   easier to add new options in the future (as needed). 
   [Since changing options is usually something that will be done rarely
   once you are satisfy with the results, storing the options in a file 
   makes it easier to reuse the same options, evidently]
   
   Why xml? Easier to program (libxml2 does the parsing) and easy to
   provide default values for some.
   
-->

<options>
  <!-- The name of the enum. If absent, #define will be generated instead. -->
  <enumname> vdsErrors</enumname>
  <!-- Name of the output dir for the error header file. If absent, the 
       current directory will be used.
       
       Alternatively, you can put the directory directly in the header_name 
       element. But if you do, the "GUARD" will use that directory name. -->
  <header_name_dir> include/vdsf </header_name_dir>
  <!-- The file name for the .h file which will hold the errors. -->
  <header_name> vdsErrors.h </header_name>
  <!-- Name of the output dir for the code to retrieve the error messages. 
       If absent, the current directory will be used.

       Alternatively, you can put the directory directly in the 2 
       "errmsg_*_name" elements. If you do, the "GUARD" will use that 
       directory name and the .c file will include the header using the 
       full name (errmsg_header_name) -->
   <errmsg_dir> engine </errmsg_dir>
  <!-- The file name for the .h file for the code to retrieve the error 
       messages. -->
  <errmsg_header_name> VdsErrorHandler.h </errmsg_header_name>
  <!-- The file name for the .c file for the code to retrieve the error 
       messages. -->
  <errmsg_c_name> VdsErrorHandler.c </errmsg_c_name>
  <!-- Prefix to be used for the error codes (enum or #define). -->
  <prefix_error> VDS </prefix_error>
  <!-- Prefix to be used for all variables in the code to retrieve the 
       error messages -->
  <prefix_variable> vdse </prefix_variable>
  <!-- How to handle the error message. The problem: the generated C strings
       will be use, eventually, by standard C/C++ libraries and some 
       sequence of characters could have some bad side effects, possibly
       including security issues.
       The defaults:
         - escape sequences are not permitted (a more fine grain approach
           could be written if the need arise).
         - quotes (' and ") are allowed (and will be escaped as needed) 
         - The % symbol. No default. I recommend the textual "percent" 
           (% is the most problematic one, IMHO. %d %p, etc are interpreted
           differently by libc (printf()) and the iostream library (cout) -->         
  <err_msg percent="percent" />
</options>

=== dprevost/errorparser/tests/options/generic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM 
             "http://errorparser.sourceforge.net/xml/errorParserOptions10.dtd">
<!-- 
   This xml file provides the options to the errorParser program.
   
   Why a file? The number of options was getting too large. Using a file
   makes it easier to manage all these options and it will also make 
   easier to add new options in the future (as needed). 
   [Since changing options is usually something that will be done rarely
   once you are satisfy with the results, storing the options in a file 
   makes it easier to reuse the same options, evidently]
   
   Why xml? Easier to program (libxml2 does the parsing) and easy to
   provide default values for some.
   
-->

<options>
  <!-- The name of the enum. If absent, #define will be generated instead. -->
  <enumname> enumErrors</enumname>
  <!-- Name of the output dir for the error header file. If absent, the 
       current directory will be used.
       
       Alternatively, you can put the directory directly in the header_name 
       element. But if you do, the "GUARD" will use that directory name. -->
  <header_name_dir> junk </header_name_dir>
  <!-- The file name for the .h file which will hold the errors. -->
  <header_name> errors.h </header_name>
  <!-- Name of the output dir for the code to retrieve the error messages. 
       If absent, the current directory will be used.

       Alternatively, you can put the directory directly in the 2 
       "errmsg_*_name" elements. If you do, the "GUARD" will use that 
       directory name and the .c file will include the header using the 
       full name (errmsg_header_name) -->
   <errmsg_dir> junk </errmsg_dir>
  <!-- The file name for the .h file for the code to retrieve the error 
       messages. -->
  <errmsg_header_name> getError.h </errmsg_header_name>
  <!-- The file name for the .c file for the code to retrieve the error 
       messages. -->
  <errmsg_c_name> getError.c </errmsg_c_name>
  <!-- Prefix to be used for the error codes (enum or #define). -->
  <prefix_error> MY_PROG </prefix_error>
  <!-- Prefix to be used for all variables in the code to retrieve the 
       error messages -->
  <prefix_variable> prog </prefix_variable>
  <!-- How to handle the error message. The problem: the generated C strings
       will be use, eventually, by standard C/C++ libraries and some 
       sequence of characters could have some bad side effects, possibly
       including security issues.
       The defaults:
         - escape sequences are not permitted (a more fine grain approach
           could be written if the need arise).
         - quotes (' and ") are allowed (and will be escaped as needed) 
         - The % symbol. No default. I recommend the textual "percent" 
           (% is the most problematic one, IMHO. %d %p, etc are interpreted
           differently by libc (printf()) and the iostream library (cout) -->         
  <err_msg percent="percent" />
  <!-- The language that will be selected for the error messages and 
       documentation. 
       If absent, the first <message> tag will be used.
       
       For each error, if there are no <message> for the selected language
       the first <message> tag will be used. -->
  <selected_lang xml:lang="en"/>
</options>
