=== dprevost/errorparser/DTD/errorParser.dtd
<!-- $Id$

    Document Type Definition for Error Parser.
    
    Copyright (C) 2008 Daniel Prevost.
 
    This file may be distributed and/or modified under the terms of the
    MIT License as described by the Open Source Initiative
    (http://opensource.org/licenses/mit-license.php) and appearing in
    the file COPYING included in the packaging of the Error Parser software.
-->

<!--
    Usage:
    
    The following public identifier can be used to identify it:

     "-//Error Parser project//DTD Error Parser XML V1.0//EN"

    The full DOCTYPE declaration should look like this:
    
    <!DOCTYPE errorlist PUBLIC "-//Error Parser project//DTD Error Parser XML V1.0//EN"
                 "http://errorparser.sourceforge.net/xml/1.0/errorParser.dtd">
-->

<!ELEMENT errorlist     (copyright?,enumname?,prefix,group+)>
<!ELEMENT copyright     (years,authors,notice+)>
<!ELEMENT years         (#PCDATA)>
<!ELEMENT authors       (#PCDATA)>
<!ELEMENT notice        (#PCDATA)>
<!ELEMENT enumname      (#PCDATA)>
<!ELEMENT prefix        (#PCDATA)>
<!ELEMENT group         (groupident?,error+)>
<!ELEMENT groupident    (#PCDATA)>
<!ELEMENT error         (number,name,messages)>
<!ELEMENT number        (#PCDATA)>
<!ELEMENT name          (#PCDATA)>
<!ELEMENT messages      (errormsg+,documentation*)>
<!ELEMENT errormsg      (#PCDATA)>
<!ELEMENT documentation (paragraph+)>
<!ELEMENT paragraph     (#PCDATA)>

<!ATTLIST errorlist version CDATA #REQUIRED>
<!ATTLIST documentation  xml:lang CDATA 'en'>
<!ATTLIST errormsg   xml:lang CDATA 'en'>
<!ATTLIST groupident xml:lang CDATA 'en'>

=== dprevost/errorparser/tests/test_no_copyright.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errorlist PUBLIC "-//Error Parser project//DTD Error Parser XML V1.0//EN"
             "http://errorparser.sourceforge.net/xml/1.0/errorParser.dtd"> 

<!-- A single group and erreur -->

<errorlist version="0.1">
  <!-- Copyright information and any additional info that will appear at 
       the top of the generated files. This is optional. -->
  <!-- The prefix will be used to label the errors (enums or defines).
       For example, the error OK would then become 
       #define TEST_OK 0 (or the enum equivalent) -->
  <prefix> test  </prefix>
  <group>
    <groupident> 
      A dummy group identifier to test if this works. 
    </groupident>
    <error>
      <number> 0 </number>
      <name> OK </name>
      <messages>
        <errormsg>No error</errormsg>
      </messages>
    </error>
    <error>
      <number> 1 </number>
      <name> INTERNAL_ERROR </name>
      <messages>
        <errormsg>Abnormal internal error - it should not happen!</errormsg>
      </messages>
    </error>
    <error>
      <number> 2 </number>
      <name> ENGINE_BUSY </name>
      <messages>
        <errormsg>
          Cannot get a lock on a system object, the engine is "busy"
        </errormsg>
        <documentation>
          <paragraph>
            This might be the result of either a very busy system where 
            unused cpu cycles are rare or a lock might be held by a 
            crashed process.
          </paragraph>
        </documentation>
      </messages>
    </error>
  </group>
  <group>
    <groupident>The following errors are network related. </groupident>
    <error>
      <number> 25 </number>
      <name> SOCKET_ERROR </name>
      <messages>
        <errormsg>
          Generic socket error.
        </errormsg>
      </messages>
    </error>
  </group>
</errorlist>

=== dprevost/errorparser/tests/test_no_groupident.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errorlist PUBLIC "-//Error Parser project//DTD Error Parser XML V1.0//EN"
             "http://errorparser.sourceforge.net/xml/1.0/errorParser.dtd"> 

<!-- A single group and erreur -->

<errorlist version="0.1">
  <!-- Copyright information and any additional info that will appear at 
       the top of the generated files. This is optional. -->
  <copyright>
    <years>2008</years>
    <authors>
      D. Prevost
    </authors>
    <!-- Each <notice> is a paragraph (to make the text easier to read) -->
    <notice>
      This file is both a test and an example.
    </notice>
    <notice>
      This file may be distributed and/or modified under the terms of the
      MIT License as described by the Open Source Initiative
      (http://opensource.org/licenses/mit-license.php) and appearing in
      the file COPYING included in the packaging of this software.
    </notice>
    <notice>
      This program is distributed in the hope that it will be useful, but
      WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
      implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    </notice>
  </copyright>
  <!-- The prefix will be used to label the errors (enums or defines).
       For example, the error OK would then become 
       #define TEST_OK 0 (or the enum equivalent) -->
  <prefix> test  </prefix>
  <group>
    <error>
      <number> 0 </number>
      <name> OK </name>
      <messages>
        <errormsg>No error</errormsg>
      </messages>
    </error>
    <error>
      <number> 1 </number>
      <name> INTERNAL_ERROR </name>
      <messages>
        <errormsg>Abnormal internal error - it should not happen!</errormsg>
      </messages>
    </error>
    <error>
      <number> 2 </number>
      <name> ENGINE_BUSY </name>
      <messages>
        <errormsg>
          Cannot get a lock on a system object, the engine is "busy"
        </errormsg>
        <documentation>
          <paragraph>
            This might be the result of either a very busy system where 
            unused cpu cycles are rare or a lock might be held by a 
            crashed process.
          </paragraph>
        </documentation>
      </messages>
    </error>
  </group>
  <group>
    <groupident>The following errors are network related. </groupident>
    <error>
      <number> 25 </number>
      <name> SOCKET_ERROR </name>
      <messages>
        <errormsg>
          Generic socket error.
        </errormsg>
      </messages>
    </error>
  </group>
</errorlist>
